nginx:
  build: images/nginx
  command: nginx -g "daemon off;"
  links:
    - php
  ports:
    - "80:80"
php:
  build: images/php
  volumes:
    - ./images/php:/var/www/html
  working_dir: /var/www/html/app/public
  command: php-fpm
  links:
    - mysql
    - cache
  ports:
    - "9000:9000"
  environment:
    APP_ENV: production
    APP_DEBUG: 'false'
    APP_KEY: 123456789ABCDE
    APP_LOCALE: en
    APP_FALLBACK_LOCALE: en
    DB_CONNECTION: mysql
    DB_HOST: db
    DB_DATABASE: appbilltax_DB789
    DB_USERNAME: root
    DB_PASSWORD: root
    MEMCACHED_HOST: cache
    CACHE_DRIVER: memcached
mysql:
  image: mysql:5.6.40
  volumes:
      - dbdata:/var/lib/mysql
  ports:
    - "3306:3306"
  environment:
    MYSQL_ROOT_PASSWORD: root
    MYSQL_DATABASE: appbilltax_DB789
    MYSQL_USER: root
    MYSQL_PASSWORD: root
cache:
  image: memcached
