#FROM mysql

# Add a database
#ENV MYSQL_DATABASE appbilltax_DB789

#RUN /etc/init.d/mysql start
#RUN mysql -u root -p${MYSQL_ROOT_PASSWORD} -e "CREATE DATABASE lba"
#RUN mysql -u root -p${MYSQL_ROOT_PASSWORD} -D lba < /usr/sql/sources.sql